export const ASSIGNMENTS = {
    // 1-Working-with-json
    ASSIGNMENT_1: 'ASSIGNMENT_1',
    ASSIGNMENT_1_SOL: 'ASSIGNMENT_1_SOL',
    // 2-
};

export const ACTIVE_ASSIGNMENT = ASSIGNMENTS.ASSIGNMENT_1_SOL;
